name: Actions CI

on:
  pull_request:
    paths-ignore:
      - '**.md'

  push:
    paths-ignore:
      - '**.md'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js v14
      uses: actions/setup-node@v1
      with:
        node-version: 14
    - name: yarn install and lint
      run: |
        yarn --frozen-lockfile
        yarn lint
        yarn compile:test
